import type { Metadata } from "next";
import Link from "next/link";
import { Geist, Geist_Mono, Kantumruy_Pro } from "next/font/google";
import "./globals.css";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const kantumruy = Kantumruy_Pro({
  variable: "--font-kantumruy-pro",
});

export const metadata: Metadata = {
  title: "Home",
  description: "Generated by create next app",
  metadataBase: new URL(
    process.env.NEXT_PUBLIC_SITE_URL ??
      (process.env.VERCEL_URL
        ? `https://${process.env.VERCEL_URL}`
        : "http://localhost:3000"),
  ),
  openGraph: {
    images: [
      {
        url: "/thumbnail.png",
        width: 1920,
        height: 1080,
        alt: "M2 website preview",
      },
    ],
  },
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      className={`${kantumruy.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="flex min-h-full flex-col">
        <header className="border-b bg-white/95">
          <nav className="mx-auto flex w-full max-w-7xl items-center justify-between px-6 py-5 sm:px-10 lg:px-16">
            <Link href="/" className="text-xl font-bold tracking-tight">M2</Link>
            <div className="flex items-center gap-6 text-sm font-medium">
              <Link href="/product" className="text-muted-foreground hover:text-foreground">Collection</Link>
              <Link href="/data-tables" className="text-muted-foreground hover:text-foreground">Table</Link>
              <Link href="/about" className="text-muted-foreground hover:text-foreground">About</Link>
            </div>
          </nav>
        </header>
        <div className="flex-1">{children}</div>
        <footer className="border-t px-6 py-8 sm:px-10 lg:px-16">
          <div className="mx-auto flex max-w-7xl justify-between gap-4 text-sm text-muted-foreground">
            <span>M2 / Considered everyday goods</span>
            <span>© 2026 M2</span>
          </div>
        </footer>
      </body>
    </html>
  );
}
