import Link from "next/link";
import Image from "next/image";
import { ArrowRight, Sparkles } from "lucide-react";
import type { Metadata } from "next";
import { ProductCard } from "@/components/product-card";
import { buttonVariants } from "@/components/ui/button";
import { getProducts } from "@/lib/api";

const siteUrl =
  process.env.NEXT_PUBLIC_SITE_URL ??
  (process.env.VERCEL_URL
    ? `https://${process.env.VERCEL_URL}`
    : "http://localhost:3000");

export const metadata: Metadata = {
  metadataBase: new URL(siteUrl),
  title: "NextJS Overview",
  description: "Generated by create next app",
  openGraph: {
    type: "website",
    url: siteUrl,
    title: "Create Next App",
    description: "Generated by create next app",
    images: [
      {
        url: `${siteUrl}/thumbnail.png`,
        width: 1920,
        height: 1080,
        alt: "M2 website preview",
      },
    ],
  },
  twitter: {
    card: "summary_large_image",
    images: [`${siteUrl}/thumbnail.png`],
  },
};

export default async function HomePage() {
  const products = await getProducts(8);

  return (
    <main>
      <section className="border-b bg-zinc-950 px-6 py-24 text-white sm:px-10 lg:px-16">
        <div className="mx-auto grid max-w-7xl gap-12 lg:grid-cols-[1.05fr_0.95fr] lg:items-center">
          <div>
            <div className="mb-6 inline-flex items-center gap-2 rounded-full border border-white/20 px-3 py-1 text-sm text-zinc-300">
              <Sparkles className="size-4" /> Curated everyday essentials
            </div>
            <h1 className="max-w-3xl text-5xl font-semibold tracking-tight sm:text-7xl">
              Objects with a little more character.
            </h1>
            <p className="mt-6 max-w-xl text-lg leading-8 text-zinc-400">
              Discover thoughtful clothing, home goods, and technology from our
              latest collection.
            </p>
            <Link
              href="/product"
              className={`${buttonVariants({ size: "lg" })} mt-8`}
            >
              Explore collection <ArrowRight className="size-4" />
            </Link>
          </div>
          <div className="relative aspect-[4/5] overflow-hidden rounded-2xl bg-zinc-800">
            {products[0]?.images[0] && (
              <Image
                src={products[0].images[0]}
                alt={products[0].title}
                fill
                priority
                sizes="(max-width: 1024px) 100vw, 45vw"
                className="object-cover"
              />
            )}
            <div className="absolute inset-x-0 bottom-0 bg-gradient-to-t from-black/80 to-transparent p-6 pt-24">
              <p className="text-sm uppercase tracking-[0.2em] text-zinc-300">
                Featured / 01
              </p>
              <p className="mt-2 text-xl font-medium">{products[0]?.title}</p>
              <p className="mt-1 text-sm text-zinc-400">
                From the M2 / 2026 collection
              </p>
            </div>
          </div>
        </div>
      </section>

      <section className="mx-auto max-w-7xl px-6 py-20 sm:px-10 lg:px-16">
        <div className="mb-10 flex items-end justify-between gap-4 border-b pb-6">
          <div>
            <p className="text-sm font-semibold uppercase tracking-[0.2em] text-muted-foreground">
              New arrivals
            </p>
            <h2 className="mt-2 text-3xl font-semibold tracking-tight">
              Made to be found
            </h2>
          </div>
          <p className="hidden max-w-xs text-right text-sm leading-6 text-muted-foreground md:block">
            Small details. Good materials. Pieces that earn their place.
          </p>
          <Link
            href="/product"
            className="hidden items-center gap-2 text-sm font-semibold sm:flex"
          >
            View all <ArrowRight className="size-4" />
          </Link>
        </div>
        <div className="grid gap-6 sm:grid-cols-2 lg:grid-cols-4">
          {products.map((product) => (
            <ProductCard key={product.id} product={product} />
          ))}
        </div>
      </section>
    </main>
  );
}
